### ISSUE TITLE
Windows installation failing

### ISSUE THREAD

**Issue by nwhetsell** [TeX-Live/installer#3]
Has there been a recent change to install-tl-windows.bat that isn’t reflected in this repository? Installing a minimal TeX Live scheme on Windows is failing again, possibly due to an issue with xz:

https://ci.appveyor.com/project/nwhetsell/installer#L139

**Comment by norbusan** [comment]
Yes, this repository is completely outdated ... sorry, I need to think about how to integrate it.

The appveyor build showed that a change I made today affected Windows - Windows currently ships tar, but it is a stupid borken bsdtar, so cannot be used in our setting. My change was to prefer system available programs to TL provided, and in this case the system provided tar is broken.

I changed the setup just now that on windows tar is preferred from the TL provided binary.

**Comment by nwhetsell** [comment]
> Windows currently ships tar

I’m not sure this is the case. tar is [available on AppVeyor](https://ci.appveyor.com/project/nwhetsell/installer/build/1.0.8#L4), but I don’t believe it’s bundled with any version of Windows.

**Comment by norbusan** [comment]
Ahh, so that is bad ... but I read that Windows now has tar ..
https://blogs.technet.microsoft.com/virtualization/2017/12/19/tar-and-curl-come-to-windows/

**Comment by nwhetsell** [comment]
I must not be using the latest version of Windows 10, then.

**Comment by norbusan** [comment]
I have now set up the auto-mirroring. Every 15min (7,22,37,52 to be in sync with the texlive git-svn) the files are copied over from the main texlive git-svn mirror and pushed to github, where an appveyor build and travis build is done.

This way, we get permanent testing of the current files.
