### ISSUE TITLE
Pause commands in Windows install script

### ISSUE THREAD

**Issue by nwhetsell** [TeX-Live/installer#4]
The Windows install script contains 3 [`pause`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/pause) commands:

https://github.com/TeX-Live/installer/blob/f1d44e3c359bf6ab24a09fe8237be80cf5f00ee2/install-tl-windows.bat#L18-L20

https://github.com/TeX-Live/installer/blob/f1d44e3c359bf6ab24a09fe8237be80cf5f00ee2/install-tl-windows.bat#L77-L79

https://github.com/TeX-Live/installer/blob/f1d44e3c359bf6ab24a09fe8237be80cf5f00ee2/install-tl-windows.bat#L82-L84

The one at line 78 seems to run when TeX Live is installed successfully. This can be problematic. For example, using a typical installation command on AppVeyor results in a time-out because Windows is waiting for a key press:

https://ci.appveyor.com/project/nwhetsell/installer/build/1.0.1

Piping `pause` commands to `echo` apparently doesn’t result in Windows waiting for a keypress—

https://ci.appveyor.com/project/nwhetsell/installer/build/1.0.2

—but running install-tl-windows.bat this way is likely to be atypical. What I usually do on AppVeyor is remove `pause` commands using PowerShell:

```powershell
Set-Content install-tl-windows.bat (Get-Content install-tl-windows.bat | Select-String -Pattern '^pause$' -NotMatch)
```

Would it be possible to remove the `pause` commands from install-tl-windows.bat, or at least the one at line 78?

**Comment by norbusan** [comment]
I forwarded the request to our Windows experts, someone should answer sooner or later. Thanks

**Comment by norbusan** [comment]
Comment from the main responsible

> The final pause command was introduced to make sure that the
> location of the logfile was displayed. But I see that this
> information currently is displayed in the gui, and not in the
> terminal window. So I removed this final pause command, r48351.
> 
> The other two pause commands should not get executed if the windows
> version is 7 or later.

So I guess we can close that.
