### ISSUE TITLE
Questions about the profile items

### ISSUE THREAD

**Issue by wtsnjp** [TeX-Live/installer#5]
Hi, I have two questions related to the profile items.

### Q1. Are the options with the prefix `option_` are obsolete?

I know that the options like `option_doc` and `option_src` are valid for now, but those are not mentioned in the [document](https://www.tug.org/texlive/doc/install-tl.html#PROFILES). I can see that corresponding options such as `tlpdbopt_install_docfiles` and `tlpdbopt_install_srcfiles` are the **prefered** option names (cf. [L1957-1976](https://github.com/TeX-Live/installer/blob/master/install-tl#L1957-L1976)).

```
  my %keyrename = (
    'option_doc'        => 'tlpdbopt_install_docfiles',
    'option_fmt'        => 'tlpdbopt_create_formats',
    'option_src'        => 'tlpdbopt_install_srcfiles',
    'option_sys_bin'    => 'tlpdbopt_sys_bin',
    'option_sys_info'   => 'tlpdbopt_sys_info',
    'option_sys_man'    => 'tlpdbopt_sys_man',
    'option_file_assocs' => 'tlpdbopt_file_assocs',
    'option_backupdir'  => 'tlpdbopt_backupdir',
    'option_w32_multi_user' => 'tlpdbopt_w32_multi_user',
    'option_post_code'  => 'tlpdbopt_post_code',
    'option_autobackup' => 'tlpdbopt_autobackup',
    'option_desktop_integration' => 'tlpdbopt_desktop_integration',
    'option_adjustrepo' => 'instopt_adjustrepo',
    'option_letter'     => 'instopt_letter',
    'option_path'       => 'instopt_adjustpath',
    'option_symlinks'   => 'instopt_adjustpath',
    'portable'          => 'instopt_portable',
    'option_write18_restricted' => 'instopt_write18_restricted',
  );
```

My question is: what is the current positions of the option names like `option_doc`? Are those obsolete and just being supported for the reason of compatibility? (which means users should rename those old names to the new ones gradually)

### Q2. Why the expranations of the "tlpdb options" are not in the document?

In the the section of "tlpdb options" of the same [install-tl document](https://www.tug.org/texlive/doc/install-tl.html#PROFILES), it refers the source code (`tlpkg/TeXLive/TLConfig.pm`) and the explanation for each item is not explicitly written. Is there any reason for that?

If those are not written just because it is WIP, that's of course fine, but I'd like to write those because it seems those options have high demand at least for the people arround me (but maybe more than that). I think just a short comments (even just copy & pasting from the comments in the source code) would work fine. On the other hand, in case there are other reasons such as "those are not stable at this point", I will not touch to the section.

**Comment by kberry** [comment]
we (really norbert) renamed the options for consistency and clarity, but we have no plans to ever remove the old names. on the other hand, i don't much want to document the old names, just for the sake of brevity.

the lack of documentation doesn't have any deep reason, we just haven't gotten around to it. it seemed to us that few people ever looked inside profile files, so not a priority. if you feel like sending a patch, that would be great. the names are stable at this point as far as i know, i feel like nothing has changed in a couple of years.

thanks.

**Comment by norbusan** [comment]
Hi

concerning Q1, yes, they are here just for backward compatibility. It is now years that we changed it, so in principle the backward handling could be dropped altogether I think.

ad Q2. We didn't include the actual opts and explanations in the install-tl document, because at that point back in time they were changing and new options added regularly. This time has passed, and so I think at the moment the options are so stable that they could be copied into the document, too, but then ... as Karl said, patches are welcome ;-)

**Comment by wtsnjp** [comment]
Thank you, both of you. I would like to find time to add the comments to the document and hopefully send a patch.

**Comment by kberry** [comment]
i don't want to disable the old names. ever. i am sure that people still have old profiles hanging around using the old names, because i am one of them. i see no reason to gratuitously break them just for the sake of minor code cleanup. smells like people switching to c++1[14...] : ).

**Comment by norbusan** [comment]
Ok, fine with me!
